const ACCESS_TOKEN_EXPIRY_TIME = "10s";
const REFRESH_TOKEN_EXPIRY_TIME = "30s";
const EMAIL_VERIFICATION_TOKEN_EXPIRY_TIME = "1d";

module.exports = {
  ACCESS_TOKEN_EXPIRY_TIME,
  REFRESH_TOKEN_EXPIRY_TIME,
  EMAIL_VERIFICATION_TOKEN_EXPIRY_TIME,
};
