# fly.toml app configuration file generated for apikeyper-node on 2024-12-16T15:28:13+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apikeyper-node'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
